// Code generated by goctl. DO NOT EDIT.
// Source: zerorpc.proto

package zerorpcclient

import (
	"context"

	"github.com/qiushenglei/gozero/rpc/zerorpc/zerorpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = zerorpc.Request
	Response = zerorpc.Response

	Zerorpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultZerorpc struct {
		cli zrpc.Client
	}
)

func NewZerorpc(cli zrpc.Client) Zerorpc {
	return &defaultZerorpc{
		cli: cli,
	}
}

func (m *defaultZerorpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := zerorpc.NewZerorpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
